# Generated by Django 2.1.7 on 2019-03-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
