# Generated by Django 2.1.7 on 2019-03-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0003_auto_20190308_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
